"""
Assetto Corsa shared memory structures - exact mirror of AC SDK types.
Based on the official AC UDP/SharedMemory plugin SDK (v1.8).
"""
import ctypes


class SPageFilePhysics(ctypes.Structure):
    _pack_ = 4
    _fields_ = [
        ("packetId",              ctypes.c_int),
        ("gas",                   ctypes.c_float),
        ("brake",                 ctypes.c_float),
        ("fuel",                  ctypes.c_float),
        ("gear",                  ctypes.c_int),
        ("rpms",                  ctypes.c_int),
        ("steerAngle",            ctypes.c_float),
        ("speedKmh",              ctypes.c_float),
        ("velocity",              ctypes.c_float * 3),
        ("accG",                  ctypes.c_float * 3),
        ("wheelSlip",             ctypes.c_float * 4),
        ("wheelLoad",             ctypes.c_float * 4),
        ("wheelsPressure",        ctypes.c_float * 4),
        ("wheelAngularSpeed",     ctypes.c_float * 4),
        ("tyreWear",              ctypes.c_float * 4),
        ("tyreDirtyLevel",        ctypes.c_float * 4),
        ("tyreCoreTemperature",   ctypes.c_float * 4),
        ("camberRAD",             ctypes.c_float * 4),
        ("suspensionTravel",      ctypes.c_float * 4),
        ("drs",                   ctypes.c_float),
        ("tc",                    ctypes.c_float),
        ("heading",               ctypes.c_float),
        ("pitch",                 ctypes.c_float),
        ("roll",                  ctypes.c_float),
        ("cgHeight",              ctypes.c_float),
        ("carDamage",             ctypes.c_float * 5),
        ("numberOfTyresOut",      ctypes.c_int),
        ("pitLimiterOn",          ctypes.c_int),
        ("abs",                   ctypes.c_float),
        ("kersCharge",            ctypes.c_float),
        ("kersInput",             ctypes.c_float),
        ("autoShifterOn",         ctypes.c_int),
        ("rideHeight",            ctypes.c_float * 2),
        ("turboBoost",            ctypes.c_float),
        ("ballast",               ctypes.c_float),
        ("airDensity",            ctypes.c_float),
        ("airTemp",               ctypes.c_float),
        ("roadTemp",              ctypes.c_float),
        ("localAngularVel",       ctypes.c_float * 3),
        ("finalFF",               ctypes.c_float),
        ("performanceMeter",      ctypes.c_float),
        ("engineBrake",           ctypes.c_int),
        ("ersRecoveryLevel",      ctypes.c_int),
        ("ersPowerLevel",         ctypes.c_int),
        ("ersHeatCharging",       ctypes.c_int),
        ("ersIsCharging",         ctypes.c_int),
        ("kersCurrentKJ",         ctypes.c_float),
        ("drsAvailable",          ctypes.c_int),
        ("drsEnabled",            ctypes.c_int),
        ("brakeTemp",             ctypes.c_float * 4),
        ("clutch",                ctypes.c_float),
        ("tyreTempI",             ctypes.c_float * 4),
        ("tyreTempM",             ctypes.c_float * 4),
        ("tyreTempO",             ctypes.c_float * 4),
        ("isAIControlled",        ctypes.c_int),
        ("tyreContactPoint",      ctypes.c_float * 4 * 3),
        ("tyreContactNormal",     ctypes.c_float * 4 * 3),
        ("tyreContactHeading",    ctypes.c_float * 4 * 3),
        ("brakeBias",             ctypes.c_float),
        ("localVelocity",         ctypes.c_float * 3),
    ]


class SPageFileGraphics(ctypes.Structure):
    _pack_ = 4
    _fields_ = [
        ("packetId",                    ctypes.c_int),
        ("status",                      ctypes.c_int),
        ("session",                     ctypes.c_int),
        ("currentTime",                 ctypes.c_wchar * 15),
        ("lastTime",                    ctypes.c_wchar * 15),
        ("bestTime",                    ctypes.c_wchar * 15),
        ("split",                       ctypes.c_wchar * 15),
        ("completedLaps",               ctypes.c_int),
        ("position",                    ctypes.c_int),
        ("iCurrentTime",                ctypes.c_int),
        ("iLastTime",                   ctypes.c_int),
        ("iBestTime",                   ctypes.c_int),
        ("sessionTimeLeft",             ctypes.c_float),
        ("distanceTraveled",            ctypes.c_float),
        ("isInPit",                     ctypes.c_int),
        ("currentSectorIndex",          ctypes.c_int),
        ("lastSectorTime",              ctypes.c_int),
        ("numberOfLaps",                ctypes.c_int),
        ("tyreCompound",                ctypes.c_wchar * 33),
        ("replayTimeMultiplier",        ctypes.c_float),
        ("normalizedCarPosition",       ctypes.c_float),
        ("activeCars",                  ctypes.c_int),
        ("carCoordinates",              ctypes.c_float * 60 * 3),
        ("carID",                       ctypes.c_int * 60),
        ("playerCarID",                 ctypes.c_int),
        ("penaltyTime",                 ctypes.c_float),
        ("flag",                        ctypes.c_int),
        ("penalty",                     ctypes.c_int),
        ("idealLineOn",                 ctypes.c_int),
        ("isInPitLane",                 ctypes.c_int),
        ("surfaceGrip",                 ctypes.c_float),
        ("mandatoryPitDone",            ctypes.c_int),
        ("windSpeed",                   ctypes.c_float),
        ("windDirection",               ctypes.c_float),
        ("isSetupMenuVisible",          ctypes.c_int),
        ("mainDisplayIndex",            ctypes.c_int),
        ("secondaryDisplayIndex",       ctypes.c_int),
        ("tc",                          ctypes.c_int),
        ("tcCut",                       ctypes.c_int),
        ("engineMap",                   ctypes.c_int),
        ("abs",                         ctypes.c_int),
        ("fuelXLap",                    ctypes.c_float),
        ("rainLights",                  ctypes.c_int),
        ("flashingLights",              ctypes.c_int),
        ("lightsStage",                 ctypes.c_int),
        ("exhaustTemperature",          ctypes.c_float),
        ("wiperLV",                     ctypes.c_int),
        ("driverStintTotalTimeLeft",    ctypes.c_int),
        ("driverStintTimeLeft",         ctypes.c_int),
        ("rainTyres",                   ctypes.c_int),
        ("sessionIndex",                ctypes.c_int),
        ("usedFuel",                    ctypes.c_float),
        ("deltaLapTime",                ctypes.c_wchar * 15),
        ("iDeltaLapTime",               ctypes.c_int),
        ("estimatedLapTime",            ctypes.c_wchar * 15),
        ("iEstimatedLapTime",           ctypes.c_int),
        ("isDeltaPositive",             ctypes.c_int),
        ("iSplit",                      ctypes.c_int),
        ("isValidLap",                  ctypes.c_int),
        ("fuelEstimatedLaps",           ctypes.c_float),
        ("trackStatus",                 ctypes.c_wchar * 33),
        ("missingMandatoryPits",        ctypes.c_int),
        ("clock",                       ctypes.c_float),
        ("directionLightsLeft",         ctypes.c_int),
        ("directionLightsRight",        ctypes.c_int),
        ("globalYellow",                ctypes.c_int),
        ("globalYellow1",               ctypes.c_int),
        ("globalYellow2",               ctypes.c_int),
        ("globalYellow3",               ctypes.c_int),
        ("globalWhite",                 ctypes.c_int),
        ("globalGreen",                 ctypes.c_int),
        ("globalChequered",             ctypes.c_int),
        ("globalRed",                   ctypes.c_int),
        ("mfdTyreSet",                  ctypes.c_int),
        ("mfdFuelToAdd",                ctypes.c_float),
        ("mfdTyrePressureLF",           ctypes.c_float),
        ("mfdTyrePressureRF",           ctypes.c_float),
        ("mfdTyrePressureLR",           ctypes.c_float),
        ("mfdTyrePressureRR",           ctypes.c_float),
        ("trackGripStatus",             ctypes.c_int),
        ("rainIntensity",               ctypes.c_int),
        ("rainIntensityIn10min",        ctypes.c_int),
        ("rainIntensityIn30min",        ctypes.c_int),
        ("currentTyreSet",              ctypes.c_int),
        ("mobileDisplayUnit",           ctypes.c_int),
        ("hardwareSettingsChanged",     ctypes.c_int),
        ("hardwareSettingsChangedCount", ctypes.c_int),
    ]


class SPageFileStatic(ctypes.Structure):
    _pack_ = 4
    _fields_ = [
        ("smVersion",               ctypes.c_wchar * 15),
        ("acVersion",               ctypes.c_wchar * 15),
        ("numberOfSessions",        ctypes.c_int),
        ("numCars",                 ctypes.c_int),
        ("carModel",                ctypes.c_wchar * 33),
        ("track",                   ctypes.c_wchar * 33),
        ("playerName",              ctypes.c_wchar * 33),
        ("playerSurname",           ctypes.c_wchar * 33),
        ("playerNick",              ctypes.c_wchar * 33),
        ("sectorCount",             ctypes.c_int),
        ("maxTorque",               ctypes.c_float),
        ("maxPower",                ctypes.c_float),
        ("maxRpm",                  ctypes.c_int),
        ("maxFuel",                 ctypes.c_float),
        ("suspensionMaxTravel",     ctypes.c_float * 4),
        ("tyreRadius",              ctypes.c_float * 4),
        ("maxTurboBoost",           ctypes.c_float),
        ("deprecated_1",            ctypes.c_float),
        ("deprecated_2",            ctypes.c_float),
        ("penaltiesEnabled",        ctypes.c_int),
        ("aidFuelRate",             ctypes.c_float),
        ("aidTireRate",             ctypes.c_float),
        ("aidMechanicalDamage",     ctypes.c_float),
        ("aidAllowTyreBlankets",    ctypes.c_int),
        ("aidStability",            ctypes.c_float),
        ("aidAutoClutch",           ctypes.c_int),
        ("aidAutoBlip",             ctypes.c_int),
        ("hasDRS",                  ctypes.c_int),
        ("hasERS",                  ctypes.c_int),
        ("hasKERS",                 ctypes.c_int),
        ("kersMaxJ",                ctypes.c_float),
        ("engineBrakeSettingsCount", ctypes.c_int),
        ("ersPowerControllerCount", ctypes.c_int),
        ("trackSPlineLength",       ctypes.c_float),
        ("trackConfiguration",      ctypes.c_wchar * 33),
        ("ersMaxJ",                 ctypes.c_float),
        ("isTimedRace",             ctypes.c_int),
        ("hasExtraLap",             ctypes.c_int),
        ("carSkin",                 ctypes.c_wchar * 33),
        ("reversedGridPositions",   ctypes.c_int),
        ("PitWindowStart",          ctypes.c_int),
        ("PitWindowEnd",            ctypes.c_int),
        ("isOnline",                ctypes.c_int),
        ("dryTyresName",            ctypes.c_wchar * 33),
        ("wetTyresName",            ctypes.c_wchar * 33),
    ]


# AC status enum values
class ACStatus:
    OFF = 0
    REPLAY = 1
    LIVE = 2
    PAUSE = 3


# AC session type enum values
class ACSessionType:
    UNKNOWN = -1
    PRACTICE = 0
    QUALIFY = 1
    RACE = 2
    HOTLAP = 3
    TIME_ATTACK = 4
    DRIFT = 5
    DRAG = 6
